name: Build Kernel (3.4)
on:
  workflow_dispatch:
    inputs:
      FIRMWARE:
        description: 'Choose a firmware:'
        required: true
        default: 'linux'
        type: choice
        options:
          - 'linux'
          - 'core-qt'
          - 'android'

jobs:
  build:
    name: Build Kernel (3.4) by ${{ github.actor }}
    runs-on: ubuntu-22.04
    steps:

      - name: Set Beijing timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: Set SWAP to 5GiB
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: Initialize compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install git automake build-essential bc python2 u-boot-tools -y
          sudo rm /bin/python
          sudo ln /bin/python2 /bin/python
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
          
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 1

      - name: Get Toolchain
        run: |
          git clone -q https://github.com/KopsourcesORG/arm-cortexa9-linux-gnueabihf-4.9.3-20160512.git --depth 1 gcc

      - name: Build Kernel
        run: |
          export KBUILD_BUILD_HOST=Github-Action
          export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
          export ARCH="arm"
          export SUBARCH="arm"
          export PATH="$GITHUB_WORKSPACE/gcc/bin:$PATH"
          export CC="gcc"
          export CROSS_COMPILE="arm-cortexa9-linux-gnueabihf-"
          make nanopi2_${{ github.event.inputs.FIRMWARE }}_defconfig
          make -j$(nproc --all) uImage
          
      - name: Upload Kernel Package
        uses: actions/upload-artifact@v4
        with:
          name: Kernel_3.4_${{ env.BUILD_TIME }}
          path: arch/arm/boot/*Image*
          
  build-hdmi:
    if: inputs.FIRMWARE != 'android'
    name: Build Kernel HDMI (3.4) by ${{ github.actor }}
    runs-on: ubuntu-22.04
    steps:

      - name: Set Beijing timezone
        uses: szenius/set-timezone@v1.2
        with:
          timezoneLinux: "Asia/Shanghai"

      - name: Set SWAP to 5GiB
        uses: pierotofy/set-swap-space@master
        with:
          swap-size-gb: 5

      - name: Initialize compilation environment
        run: |
          sudo apt-get update
          sudo apt-get install git automake build-essential bc python2 u-boot-tools -y
          sudo rm /bin/python
          sudo ln /bin/python2 /bin/python
          echo "BUILD_TIME=$(TZ=Asia/Shanghai date "+%Y%m%d%H%M")" >> $GITHUB_ENV
          
      - name: Checkout Repository
        uses: actions/checkout@v4
        with: 
          fetch-depth: 1

      - name: Get Toolchain
        run: |
          git clone -q https://github.com/KopsourcesORG/arm-cortexa9-linux-gnueabihf-4.9.3-20160512.git --depth 1 gcc

      - name: Build Kernel
        run: |
          export KBUILD_BUILD_HOST=Github-Action
          export KBUILD_BUILD_USER=$(echo ${{ github.actor }} | tr A-Z a-z)
          export ARCH="arm"
          export SUBARCH="arm"
          export PATH="$GITHUB_WORKSPACE/gcc/bin:$PATH"
          export CC="gcc"
          export CROSS_COMPILE="arm-cortexa9-linux-gnueabihf-"
          make nanopi2_${{ github.event.inputs.FIRMWARE }}_hdmi_defconfig
          make -j$(nproc --all) uImage
          
      - name: Upload Kernel Package
        uses: actions/upload-artifact@v4
        with:
          name: Kernel_hdmi_3.4_${{ env.BUILD_TIME }}
          path: arch/arm/boot/*Image*
          